const plans = {
  silver: [
    {
      varient: "default",
      refferalCode: "DEFSIL",
      ttl: "9999",
      name: "Silver Plan",
      price: "Rs. 1099",
      duration: "1 day",
      description: [
        "One day All-Access Pass",
        "Budget friendly",
        "Meals & Accommodation included",
        "DJ night access",
      ],
      gradient: "bg-gradient-to-r from-gray-500 to-gray-300",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1099.00&cu=INR&aid=uGICAgKDApojPLA",
    },
    {
      varient: "discountMSIT",
      refferalCode: "SIL200",
      ttl: "50",
      name: "Silver Plan",
      price: "Rs. 1099",
      duration: "1 day",
      description: [
        "One day All-Access Pass",
        "Budget friendly",
        "Meals & Accommodation included",
        "DJ night access",
      ],
      gradient: "bg-gradient-to-r from-gray-500 to-gray-300",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1099.00&cu=INR&aid=uGICAgKDApojPLA",
    },
  ],
  gold: [
    {
      varient: "default",
      refferalCode: "DEFGLD",
      ttl: "9999",
      name: "Gold Plan",
      price: "Rs. 1499",
      duration: "2 days",
      description: [
        "Affordable All-Access Pass",
        "Full Access to All Events for 2 Days",
        "Convenient On-Campus Stay",
        "Exclusive Entry to DJ Night",
      ],
      gradient: "bg-gradient-to-r from-yellow-400 to-yellow-200",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1499.00&cu=INR&aid=uGICAgKDApojPLA",
    },
    {
      varient: "discountMSIT",
      refferalCode: "GLD200",
      ttl: "50",
      name: "Gold Plan",
      price: "Rs. 1499",
      duration: "2 days",
      description: [
        "Affordable All-Access Pass",
        "Full Access to All Events for 2 Days",
        "Convenient On-Campus Stay",
        "Exclusive Entry to DJ Night",
      ],
      gradient: "bg-gradient-to-r from-yellow-400 to-yellow-200",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1499.00&cu=INR&aid=uGICAgKDApojPLA",
    },
  ],
  platinum: [
    {
      varient: "default",
      refferalCode: "DEFPLT",
      ttl: "9999",
      name: "Platinum Plan",
      price: "Rs. 1799",
      duration: "3 days",
      description: [
        "All-Access Adventure for 3 days",
        "Hassle-Free Travel",
        "Meals and Accommodation inclusive",
        "Exclusive DJ Night Access",
        "Comfortable Stay",
        "Infinix Zone Pass",
      ],
      gradient: "bg-gradient-to-r from-purple-500 to-purple-300",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1799.00&cu=INR&aid=uGICAgKDApojPLA",
    },
    {
      varient: "discountMSIT",
      refferalCode: "PLT200",
      ttl: "50",
      name: "Platinum Plan",
      price: "Rs. 1799",
      duration: "3 days",
      description: [
        "All-Access Adventure for 3 days",
        "Hassle-Free Travel",
        "Meals and Accommodation inclusive",
        "Exclusive DJ Night Access",
        "Comfortable Stay",
        "Infinix Zone Pass",
      ],
      gradient: "bg-gradient-to-r from-purple-500 to-purple-300",
      link: "upi://pay?pa=aroraxjatin@oksbi&pn=Jatin%20Arora&am=1799.00&cu=INR&aid=uGICAgKDApojPLA",
    },
  ],
};

export default plans;
